// Generated by `npm run pull` — do not edit manually
// Run `npm run pull` to regenerate from the connected BEP

export interface BepEffects {
  'hello-effect': () => void
}

export interface BepAutomations {
  'hello-automation': () => { eventId: string }
}

export interface BepResolvers {
  'hello-resolver': (url: string) => unknown
}

export interface BepAdapters {
  'hello-adapter': (data: unknown) => unknown
}

export interface BepTypes {
  effects:     BepEffects
  automations: BepAutomations
  resolvers:   BepResolvers
  adapters:    BepAdapters
}
